/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import javax.swing.JOptionPane;
import logica.usuarioLogica;
import modelo.Cliente;
import modelo.Reserva;

/**
 *
 * @author Usuario
 */
public class CancelarReserva extends javax.swing.JFrame {
    
    private usuarioLogica usuario = new usuarioLogica();
    Cliente cliente;
    List<Reserva> listReserva;

    /**
     * Creates new form CancelarReserva
     */
    public CancelarReserva() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        listReservDisp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cancelarR = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        consultarCli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cancelar Reserva");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 233, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 76, 110, 25));
        getContentPane().add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 76, 134, 25));

        listReservDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listReservDispActionPerformed(evt);
            }
        });
        getContentPane().add(listReservDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 119, 134, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Reservas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 119, 110, 28));

        cancelarR.setText("Cancelar Reserva");
        cancelarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 175, -1, -1));

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        consultarCli.setText("Consultar");
        consultarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCliActionPerformed(evt);
            }
        });
        getContentPane().add(consultarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondoPequeño.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 460, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listReservDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listReservDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listReservDispActionPerformed

    private void cancelarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRActionPerformed
        int reserv = Integer.valueOf(listReservDisp.getSelectedItem().toString());
        Reserva reservaN = usuario.consultarReserva(reserv);
        reservaN.setEstado("Cancelada");
        usuario.modificarReserva(reservaN);
        
        JOptionPane.showMessageDialog(this, "La reserva se ha cancelado satisfactoriamente");
        
        Recepcionist recep  = new Recepcionist();
        recep.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_cancelarRActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Recepcionist recep  = new Recepcionist();
        recep.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void consultarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCliActionPerformed
        listReserva = usuario.reservas();
        cliente = usuario.retornarCliente(idCliente.getText());   
        listReservDisp.setModel(new javax.swing.DefaultComboBoxModel<>(usuario.reservasHechas(listReserva, cliente)));
    }//GEN-LAST:event_consultarCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton cancelarR;
    private javax.swing.JButton consultarCli;
    private javax.swing.JTextField idCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> listReservDisp;
    // End of variables declaration//GEN-END:variables
}
