/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.usuarioLogica;
import modelo.Cliente;
import modelo.Reserva;
import persistencia.ClienteJpaController;
import persistencia.ReservaJpaController;
import persistencia.exceptions.NonexistentEntityException;
import vista.Recepcionist;
import vista.RegReserva;

/**
 *
 * @author Usuario
 */
public class Hospedaje extends javax.swing.JFrame {
    
    private ReservaJpaController reserva = new ReservaJpaController();
    private ClienteJpaController cliente = new ClienteJpaController();
    private usuarioLogica usuario = new usuarioLogica();

    /**
     * Creates new form Hospedaje
     */
    public Hospedaje() {
        super("Hospedaje");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ConsultarR = new javax.swing.JButton();
        CrearR = new javax.swing.JButton();
        ConfirmarH = new javax.swing.JButton();
        AtrasH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reservasInac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospedaje");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 20, 176, 25));

        ConsultarR.setText("Consultar Reserva");
        ConsultarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarRActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 133, -1));

        CrearR.setText("Crear Reserva");
        CrearR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRActionPerformed(evt);
            }
        });
        getContentPane().add(CrearR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 121, -1));

        ConfirmarH.setText("Confirmar Hospedaje");
        ConfirmarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarHActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        AtrasH.setText("Atras");
        AtrasH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasHActionPerformed(evt);
            }
        });
        getContentPane().add(AtrasH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Reserva:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 56, 133, 26));

        getContentPane().add(reservasInac, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 54, 121, 23));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondoPequeño.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 390, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarRActionPerformed
        
        //try {
            String idReserv = JOptionPane.showInputDialog(null, "Ingrese el ID del cliente", 
                    "Consultar Reserva", JOptionPane.INFORMATION_MESSAGE);
            reservasInac.setModel(new javax.swing.DefaultComboBoxModel<>(usuario.buscarReservaInactiva(idReserv)));
        
    }//GEN-LAST:event_ConsultarRActionPerformed

    private void CrearRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRActionPerformed
        RegReserva regR  = new RegReserva();
        regR.setVisible(true);
        dispose();
    }//GEN-LAST:event_CrearRActionPerformed

    private void ConfirmarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarHActionPerformed
        
        int codR = Integer.valueOf(reservasInac.getSelectedItem().toString());
        Recepcionist recep  = new Recepcionist();
        Reserva reservaC = usuario.consultarReserva(codR);
        reservaC.setEstado("Activa");
        
        try {
            reserva.edit(reservaC);
            
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(Hospedaje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Hospedaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        recep.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConfirmarHActionPerformed

    private void AtrasHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasHActionPerformed
        Recepcionist recep  = new Recepcionist();
        recep.setVisible(true);
        dispose();
    }//GEN-LAST:event_AtrasHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospedaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospedaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasH;
    private javax.swing.JButton ConfirmarH;
    private javax.swing.JButton ConsultarR;
    private javax.swing.JButton CrearR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> reservasInac;
    // End of variables declaration//GEN-END:variables
}
