/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import vista.RegReserva;
import vista.RegistroCliente;

/**
 *
 * @author Lenovo
 */
public class Recepcionist extends javax.swing.JFrame {

    /**
     * Creates new form Recepcionist
     */
    public Recepcionist() {
        super("Recepcionista");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrarR = new javax.swing.JButton();
        RegistrarH = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        cancelarR = new javax.swing.JButton();
        reservSalon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 245, 27));

        RegistrarR.setText("Registrar Reserva Hospedaje");
        RegistrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarRActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        RegistrarH.setText("Registrar Hospedaje");
        RegistrarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarHActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        registrarCliente.setText("Registrar Cliente");
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        cancelarR.setText("Cancelar Reserva");
        cancelarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, -1));

        reservSalon.setText("Registrar Reserva Salón");
        reservSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservSalonActionPerformed(evt);
            }
        });
        getContentPane().add(reservSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 131, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondoPequeño.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -6, 500, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarRActionPerformed
        RegReserva regR  = new RegReserva();
        regR.setVisible(true);
        dispose();   
    }//GEN-LAST:event_RegistrarRActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        Login1 log  = new Login1();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void RegistrarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarHActionPerformed
        Hospedaje hosp  = new Hospedaje();
        hosp.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegistrarHActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        RegistroCliente r = new RegistroCliente();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void cancelarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRActionPerformed
        
        
    }//GEN-LAST:event_cancelarRActionPerformed

    private void reservSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservSalonActionPerformed
        RegReservSalon r = new RegReservSalon();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_reservSalonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton RegistrarH;
    private javax.swing.JButton RegistrarR;
    private javax.swing.JButton cancelarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JButton reservSalon;
    // End of variables declaration//GEN-END:variables
}
