/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import logica.usuarioLogica;
import modelo.Cliente;
/**
 *
 * @author Usuario
 */
public class RegistroCliente extends javax.swing.JFrame {
    
    private usuarioLogica usuario = new usuarioLogica();

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        super("Registro de clientes");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCliente = new javax.swing.JLabel();
        nomCliente = new javax.swing.JLabel();
        apeCliente = new javax.swing.JLabel();
        telCliente = new javax.swing.JLabel();
        registro = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        iden = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        ape = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idCliente.setText("Identificacion:");
        idCliente.setOpaque(true);
        getContentPane().add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 23));

        nomCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomCliente.setText("Nombres:");
        nomCliente.setOpaque(true);
        getContentPane().add(nomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 23));

        apeCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apeCliente.setText("Apellidos:");
        apeCliente.setOpaque(true);
        getContentPane().add(apeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 23));

        telCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telCliente.setText("Telefono:");
        telCliente.setOpaque(true);
        getContentPane().add(telCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 23));

        registro.setText("Confirmar");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 241, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 241, -1, -1));
        getContentPane().add(iden, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, 23));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 142, 23));

        ape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeActionPerformed(evt);
            }
        });
        getContentPane().add(ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 142, 23));
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 142, 23));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 241, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondo.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        try{
            Cliente nuevoCliente = new Cliente();
            nuevoCliente.setIdentificacion(iden.getText());
            nuevoCliente.setNombres(nom.getText());
            nuevoCliente.setApellidos(ape.getText());
            nuevoCliente.setTelefono(tel.getText());
            usuario.registrarCliente(nuevoCliente);
            JOptionPane.showMessageDialog(this, "El cliente se ha registrado satisfactoriamente");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_registroActionPerformed

    private void apeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        iden.setText("");
        nom.setText("");
        ape.setText("");
        tel.setText("");
    }//GEN-LAST:event_cancelarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Recepcionist recep  = new Recepcionist();
        recep.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });

        /*Cliente nuevoCliente = new Cliente();
        nuevoCliente.setIdentificacion("123");
        nuevoCliente.setNombres("cristian");
        nuevoCliente.setApellidos("ospina");
        nuevoCliente.setTelefono("230");
        usuarioLogica u = new usuarioLogica();
        u.registrarCliente(nuevoCliente);*/
          
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape;
    private javax.swing.JLabel apeCliente;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel idCliente;
    private javax.swing.JTextField iden;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nomCliente;
    private javax.swing.JButton registro;
    private javax.swing.JTextField tel;
    private javax.swing.JLabel telCliente;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
